services:
  # 1. O Backend (Spring Boot)
  - type: web
    name: taske-backend
    env: docker
    rootDir: .
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: taske-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: taske-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: taske-db
          property: password

  # 2. O Frontend (React) - Configurado como Web Service Static
  - type: web
    name: taske-frontend
    runtime: static             # Define que é um Site Estático
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist     # Pasta onde o Vite gera os arquivos
    # plan: free (Removed to fix validation error - Static sites default to free)
    # region: removed (Static sites are global)
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: taske-backend
          property: host

databases:
  # 3. O Banco de Dados
  - name: taske-db
    databaseName: taske
    user: taskeuser
    plan: free
    region: oregon
    ipAllowList: [] # Segurança: só permite acesso interno (do backend)
